### PR TITLE
Add symlink from /usr/local/bin/python to /usr/bin/python3

### PR DESCRIPTION
**Pull request by bjeurissen**

### CODE REVIEW

**Comment by jdtournier** [comment]
Just had a go on my Intel mac mini running Ventura 13.1. Using symbolic links just doesn't seem to work...
```sh
% ln -s /usr/bin/python3 /usr/local/bin/python
% which python
/usr/local/bin/python
% python
python: error: Failed to locate 'python'.
xcode-select: Failed to locate 'python', requesting installation of command line developer tools.
```

Restarting the shell, or running versions incantations of `hash` makes no difference. [Similar issues reported elsewhere](https://serverfault.com/questions/1090205/why-doesnt-creating-a-sym-link-from-python-to-python-3-work). Seems #2539 is not done yet. Not sure how to handle this...

**Comment by jdtournier** [comment]
To be honest, at this point I reckon it's best just to replace the shebangs with what we know will work - if only for the macOS native installer... 

This seems to do the job on my system:
```
for f in $(grep -lr '^#!/usr/bin/env python'); do 
  sed -i 's|^#!/usr/bin/env python$|#!/usr/bin/python3|' $f; 
done 
```

**Comment by bjeurissen** [comment]
The only issue is that we cannot do that until we no longer support python2

**Comment by jdtournier** [comment]
I have no issues doing that on the packaging side, which this is - especially on a system we know doesn't ship with python2 by default.

**Pull request closed without merging**
